language: haskell
install:
  - git clone https://github.com/elm-lang/elm-compiler.git
  - git clone https://github.com/elm-lang/elm-package.git
  - git clone https://github.com/elm-lang/elm-make.git
  - cd elm-make
  - cabal sandbox init
  - cabal sandbox add-source ../elm-compiler
  - cabal sandbox add-source ../elm-package
  - cabal install
  - cd ..
  - npm install jsdom
before_script: 
  - ./elm-make/.cabal-sandbox/bin/elm-make --yes --output test.js test/Test.elm
script: echo "exit" | ./elm-io.sh test.js > /dev/null
