language: haskell
install:
  - echo $PATH
  - git clone https://github.com/elm-lang/Elm.git
  - cabal sandbox init
  - cabal sandbox add-source Elm
  - cabal install
  - ls .cabal-sandbox/bin
  - sudo ln -s `pwd`/.cabal-sandbox/bin/elm    /usr/local/bin/elm
  - sudo ln -s `pwd`/.cabal-sandbox/bin/elm-io /usr/local/bin/elm-io
  - ./.cabal-sandbox/bin/elm --version
  - stat ./.cabal-sandbox/bin/elm-io
  - ls /usr/local/bin
  - /usr/local/bin/elm --version
  - elm --version
  - npm install jsdom
before_script: elm-io test/Test.elm test.js
script: echo "exit" | node test.js > /dev/null
