language: haskell
install:
  - git clone https://github.com/elm-lang/Elm.git
  - cd Elm
  - cabal sandbox init
  - cabal install
  - cd ..
  - cabal sandbox add-source Elm
  - sudo ln -s ~/.cabal/bin/elm /usr/local/bin/elm
  - sudo ln -s ~/.cabal/bin/elm-io /usr/local/bin/elm-io
  - npm install jsdom
before_script: elm-io test/Test.elm test.js
script: echo "exit" | node test.js > /dev/null
