language: haskell
install:
  - git clone https://github.com/elm-lang/Elm.git
  - cabal sandbox init
  - cabal sandbox add-source Elm
  - cabal install
  - sudo cp .cabal-sandbox/bin/elm    /usr/local/bin/elm
  - sudo cp .cabal-sandbox/bin/elm-io /usr/local/bin/elm-io
  - npm install jsdom
before_script: elm-io test/Test.elm test.js
script: echo "exit" | node test.js > /dev/null
